# create this in .github/workflows/ci.yml
name: Upload release assets
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.3.2.7']
        elixir: ['1.15.7']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Make tarball
        id: make_tarball
        run: |
          make rel
          PACK_PATH=$(ls _build/default/emqx_plugrel/*.tar.gz)
          PACK_NAME=$(basename $PACK_PATH)
          echo "::set-output name=package_path::$PACK_PATH"
          echo "::set-output name=package_name::$PACK_NAME"
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.make_tarball.outputs.package_path }}
          asset_name: ${{ steps.make_tarball.outputs.package_name }}
          asset_content_type: application/zip
